### ISSUE TITLE
Consider updating install docs with anaconda

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#914]
After much trial and error, I think I have hit upon what seems to be a
reliable method at least on linux.

- Start with a fresh install of miniconda (either 2 or 3)
- conda install astropy future boost pyyaml
- scons TMV_DIR=/tmv/prefix/dir PREFIX=$HOME/miniconda3 install

Substitute miniconda2 for python2 versions.  FTW and TMV are still to be installed separately.

Note the installation of boost through conda, which seems to mitigate one of
the common failure modes I have encountered.

It might be worth adding this example to the docs.

**Comment by rmjarvis** [comment]
This sounds helpful.  Please do go ahead and edit INSTALL.md appropriately and do a PR.

**Comment by dkirkby** [comment]
Thanks for this recipe @esheldon!

For the record, here are the steps I just tried to install GalSim 1.5 in anaconda (python 3.6) using the new (python3-compatible) [scons 3.0](http://scons.org/scons-300-is-available.html).  This assumes you have already installed fftw and tmv to a system directory (`/usr/local` in my example below).

Note that I am using anaconda and installing GalSim into its own environment (rather than using miniconda and installing into the root environment).  My attempt failed (details below) so I am hoping someone here has advice or suggestions.

Create a new conda environment:
```
conda create --name galsim pip ipython jupyter numpy scipy astropy matplotlib pyyaml future boost
source activate galsim
```

Install scons 3.0 into the new environment:
```
cd scons-3.0.0
pip install .
```
Check that `which scons` reports `~/anaconda3/envs/galsim/bin/scons`.

Install GalSim
```
git clone git@github.com:GalSim-developers/GalSim.git
cd GalSim
scons TMV_DIR=/usr/local FFTW_DIR=/usr/local PREFIX=$HOME/anaconda3/envs/galsim install
```
This last step fails at the link stage with:
```
g++ -o galsim/_galsim.so -bundle pysrc/.obj/module.os pysrc/.obj/Angle.os pysrc/.obj/Bounds.os pysrc/.obj/PhotonArray.os pysrc/.obj/Image.os pysrc/.obj/SBProfile.os pysrc/.obj/SBAdd.os pysrc/.obj/SBConvolve.os pysrc/.obj/SBDeconvolve.os pysrc/.obj/SBFourierSqrt.os pysrc/.obj/SBTransform.os pysrc/.obj/SBBox.os pysrc/.obj/SBGaussian.os pysrc/.obj/SBDeltaFunction.os pysrc/.obj/SBExponential.os pysrc/.obj/SBSersic.os pysrc/.obj/SBMoffat.os pysrc/.obj/SBAiry.os pysrc/.obj/SBShapelet.os pysrc/.obj/SBInterpolatedImage.os pysrc/.obj/SBKolmogorov.os pysrc/.obj/SBSpergel.os pysrc/.obj/SBInclinedExponential.os pysrc/.obj/SBInclinedSersic.os pysrc/.obj/Random.os pysrc/.obj/Noise.os pysrc/.obj/HSM.os pysrc/.obj/Integ.os pysrc/.obj/Table.os pysrc/.obj/Interpolant.os pysrc/.obj/CorrelatedNoise.os pysrc/.obj/Bessel.os pysrc/.obj/CDModel.os pysrc/.obj/Silicon.os pysrc/.obj/RealGalaxy.os pysrc/.obj/WCS.os -Llib -L/usr/local/lib -L/Users/david/anaconda3/envs/galsim/lib -lboost_python3 -lpython3.6m -ltmv_symband -lfftw3 -ltmv -lcblas -lgalsim
Undefined symbols for architecture x86_64:
  "boost::python::objects::function_object(boost::python::objects::py_function const&, std::__1::pair<boost::python::detail::keyword const*, boost::python::detail::keyword const*> const&)", referenced from:
  ...
```
This seems to be the same C++11 problem reported [here](https://stackoverflow.com/questions/18389799/boost-python-undefined-symbols-error-even-though-the-lib-files-are-linked).  @esheldon are you using something other than the default system compiler?  I am using the Apple compiler tools included with Xcode:
```
% g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by dkirkby** [comment]
Since the problem seems to be related to incompatible versions of the C++ stdlib, I used `otool -L` (mac equivalent of `ldd`) to identify which stdlib each library is using:

- libgalsim uses
  - libc++.1
  - libtmv, libtmv_symband
     - both use libc++.1
- $HOME/anaconda3/envs/galsim/lib/libboost_python3 uses:
  - libstdc++.6

The remaining dependencies have no C++.  Note that both the C++11 [libc++](https://clang.llvm.org/cxx_status.html) and the g++(?) libstdc++ are both being used here.

It looks there are two possible solutions:
 - Build boost from source using libc++ (but the point of this recipe is to avoid this)
 - Force tmv and GalSim to use libstdc++

GalSim is already building with `-std=c++98` so I guess that is not sufficient.  Any ideas?

**Comment by dkirkby** [comment]
I just discovered [-stdlib=libstdc++](https://stackoverflow.com/questions/19774778/when-is-it-necessary-to-use-use-the-flag-stdlib-libstdc) which successfully builds tmv against libstdc++:
```
scons CXX=g++ EXTRA_FLAGS='-stdlib=libstdc++' LINKFLAGS='-stdlib=libstdc++' install
```
I'm not sure which of these options is actually required, but all together they do the job.

The corresponding updated GalSim install cmd is:
```
scons TMV_DIR=/usr/local FFTW_DIR=/usr/local PREFIX=$HOME/anaconda3/envs/galsim CXX=g++ EXTRA_FLAGS='-stdlib=libstdc++' LINKFLAGS='-stdlib=libstdc++' install
```
This works and I can import the resulting galsim library (when using the galsim conda environment)!

Note that clang now complains with:
```
clang: warning: libstdc++ is deprecated; move to libc++ [-Wdeprecated]
```
but that's the price you pay for not installing boost from source (which seems to be the main stumbling block for most new users).

**Comment by rmjarvis** [comment]
Thanks very much David for figuring this out.  You'll be heartened to hear that the next major GalSim release will probably be the one where I'm ripping out the boost dependency.  So hopefully that will save people a lot of headaches like this one.

**Comment by esheldon** [comment]
@dkirkby As I stated in my original post, I'm using linux with the default compilers.  I don't have a mac for testing.

**Comment by esheldon** [comment]
Note that new anaconda is compiled with **very** new versions of gcc.  In the past they used the 4.* series, but now are using gcc 7.2* series.  This may be related to your problem as well.

**Comment by esheldon** [comment]
relevant  https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/

**Comment by cwwalter** [comment]
> Note that new anaconda is compiled with very new versions of gcc. In the past they used the 4.* series, but now are using gcc 7.2* series. This may be related to your problem as well.

Note for LSST people: this is going to be useful because upcoming versions of the stack are going to require c++14 features.  On linux this will mean you need to use a newer compiler than supplied with CENTOS 7.  On the lsst development machines they will use devtoolset for this.  Using the conda version of the compiler should also work.

I am going to try installing the stack and stack supplied GalSim with the new conda compiler soon.

**Comment by esheldon** [comment]
I wonder if we could use the conda compilers to create binary conda distributions for TMV and Galsim (against the conda boost)

The one could simply do `conda install galsim`

**Comment by belaa** [comment]
I have already installed tmv (v. 0.75) and fftw and am following @dkirkby's recipe above to install Galsim:

```
conda create --name galsim pip ipython jupyter numpy scipy astropy matplotlib pyyaml future boost`
source activate galsim

cd scons-3.0.0
pip install .

git clone git@github.com:GalSim-developers/GalSim.git
cd GalSim
```

But when I run:

```
scons TMV_DIR=/usr/local FFTW_DIR=/usr/local PREFIX=$HOME/anaconda3/envs/galsim CXX=g++ EXTRA_FLAGS='-stdlib=libstdc++' LINKFLAGS='-stdlib=libstdc++' install
```
I get the following TMV linkage error (from config.log):

```
clang: warning: libstdc++ is deprecated; move to libc++ [-Wdeprecated]
Undefined symbols for architecture x86_64:
  "tmv::MatrixView<std::complex<double>, 0>::conjugateSelf()", referenced from:
      void tmv::Copy<double, std::complex<double> >(tmv::GenMatrix<double> const&, tmv::MatrixView<std::complex<double>, 0>) in conftest_23.o
      void tmv::Copy<std::complex<double>, std::complex<double> >(tmv::GenMatrix<std::complex<double> > const&, tmv::MatrixView<std::complex<double>, 0>) in conftest_23.o
  "tmv::MatrixView<std::complex<double>, 0>::transposeSelf()", referenced from:
      void tmv::Copy<std::complex<double>, std::complex<double> >(tmv::GenMatrix<std::complex<double> > const&, tmv::MatrixView<std::complex<double>, 0>) in conftest_23.o
  "tmv::VectorView<std::complex<double>, 0>::conjugateSelf()", referenced from:
      void tmv::Copy<std::complex<double>, double>(tmv::GenVector<double> const&, tmv::VectorView<std::complex<double>, 0>) in conftest_23.o
      void tmv::Copy<std::complex<double>, std::complex<double> >(tmv::GenVector<std::complex<double> > const&, tmv::VectorView<std::complex<double>, 0>) in conftest_23.o
```

I ran all the test executables in tmv and they passed successfully. I noticed Issue #203 also addressed SCons failing to link with tmv but the errors I'm getting are different.

**Comment by rmjarvis** [comment]
Please post the gs_error.txt file.  I'll take a look.

**Comment by belaa** [comment]
[gs_error.txt](https://github.com/GalSim-developers/GalSim/files/1691227/gs_error.txt)

**Comment by rmjarvis** [comment]
It look to me like you compiled TMV either with a different compiler or a different set of compiler flags than you are trying to compile GalSim.  Try recompiling that with
```
scons CXX=g++ EXTRA_FLAGS='-stdlib=libstdc++ -std=c++98' LINKFLAGS='-stdlib=libstdc++' install
```
and see if it helps.

**Comment by belaa** [comment]
That worked, thanks!

**Comment by rmjarvis** [comment]
@belaa Could you try installing the noboost branch, which doesn't require boost (hence the name).  You've had the most problematic installation with boost that I know about, so hopefully this will work for you and we can move toward this becoming GalSim version 2.0.

Here are the steps to try out:  (from the GalSim directory)
```
git pull
git checkout noboost
conda install -y -c conda-forge --file conda_requirements.txt
pip install -r requirements.txt
pip install .
```
(See full instructions in INSTALL.md on that branch, but that's the quick summary.)

Thanks!

**Comment by belaa** [comment]
@rmjarvis I did the steps above and successfully installed GalSim-2.0.0a0. However when I try to import galsim in ipython I run into the following error:

```In [1]: import galsim
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b4d35fa9638f> in <module>()
----> 1 import galsim

~/Documents/repos/GalSim/galsim/__init__.py in <module>()
     94 
     95 # First some basic building blocks that don't usually depend on anything else
---> 96 from .position import Position, PositionI, PositionD
     97 from .bounds import Bounds, BoundsI, BoundsD, _BoundsI, _BoundsD
     98 from .shear import Shear, _Shear

~/Documents/repos/GalSim/galsim/position.py in <module>()
     20 """
     21 
---> 22 from . import _galsim
     23 
     24 class Position(object):

ImportError: cannot import name '_galsim'
```

The file I think it's looking for `_galsim.cpython-36m-darwin.so` is in `~/anaconda3/envs/galsim/lib/python3.6/site-packages/galsim`.

**Comment by rmjarvis** [comment]
Can you try starting ipython in a different directory.  Like your home directory or something.  I think it's just getting confused by trying to import the `galsim` that is in the `GalSim` directory rather than the installed one.

**Comment by belaa** [comment]
@rmjarvis You were right, everything seems to be good now!

**Comment by rmjarvis** [comment]
Awesome!  Very glad to hear it.  :)  Now we just need to make sure @dkirkby's blending package can work with GalSim v2.0.  It should be close, but there might be some deprecations in there that need to be cleaned up.
