### ISSUE TITLE
 error: no matching function for call to ‘init(galsim::Table* (*)(size_t, size_t, int, const char*))’

### ISSUE THREAD

**Issue by gijzelaerr** [GalSim-developers/GalSim#985]
running python setup.py build on Ubuntu 18.04, python2, pybind 2.0.1, galsim version 2.0.6

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -march=native -O2 -pipe -fPIC -I/usr/include/python2.7 -Iinclude -Iinclu
de/galsim -Iinclude/fftw3 -I/usr/lib/python2.7/dist-packages/eigency/eigen_3.2.8 -I/usr/include -c pysrc/SBInclinedSersic.cpp -o build/temp.linux-x86_64-
2.7/pysrc/SBInclinedSersic.o -O2 -msse2 -std=c++11 -fvisibility=hidden
In file included from pysrc/Table.cpp:20:0:
pysrc/Table.cpp: In function ‘void galsim::pyExportTable(pybind11::module&)’:
pysrc/PyBind11Helper.h:68:39: error: no matching function for call to ‘init(galsim::Table* (*)(size_t, size_t, int, const char*))’
 #define PY_INIT(args...) py::init(args)
                                       ^
pysrc/Table.cpp:90:18: note: in expansion of macro ‘PY_INIT’
             .def(PY_INIT(&MakeTable))
                  ^~~~~~~
In file included from pysrc/PyBind11Helper.h:60:0,
                 from pysrc/Table.cpp:20:
/usr/include/pybind11/pybind11.h:1418:51: note: candidate: template<class ... Args> pybind11::detail::init<Args ...> pybind11::init()
 template <typename... Args> detail::init<Args...> init() { return detail::init<Args...>(); }
                                                   ^~~~
/usr/include/pybind11/pybind11.h:1418:51: note:   template argument deduction/substitution failed:
In file included from pysrc/Table.cpp:20:0:
pysrc/PyBind11Helper.h:68:39: note:   candidate expects 0 arguments, 1 provided
 #define PY_INIT(args...) py::init(args)
                                       ^
pysrc/Table.cpp:90:18: note: in expansion of macro ‘PY_INIT’
             .def(PY_INIT(&MakeTable))
                  ^~~~~~~
pysrc/PyBind11Helper.h:68:39: error: no matching function for call to ‘init(galsim::Table2D* (*)(size_t, size_t, size_t, int, int, const char*))’
 #define PY_INIT(args...) py::init(args)
                                       ^
pysrc/Table.cpp:95:18: note: in expansion of macro ‘PY_INIT’
             .def(PY_INIT(&MakeTable2D))
                  ^~~~~~~
In file included from pysrc/PyBind11Helper.h:60:0,
                 from pysrc/Table.cpp:20:
/usr/include/pybind11/pybind11.h:1418:51: note: candidate: template<class ... Args> pybind11::detail::init<Args ...> pybind11::init()
 template <typename... Args> detail::init<Args...> init() { return detail::init<Args...>(); }
                                                   ^~~~
/usr/include/pybind11/pybind11.h:1418:51: note:   template argument deduction/substitution failed:
In file included from pysrc/Table.cpp:20:0:
pysrc/PyBind11Helper.h:68:39: note:   candidate expects 0 arguments, 1 provided
 #define PY_INIT(args...) py::init(args)
                                       ^
```

**Comment by rmjarvis** [comment]
We require pybind11 >= 2.2.  As described in the INSTALL file and also the requirements.txt file.  Indeed, this explains why you found setup.py easy_installing pybind11 and trying to use a local copy, rather than using the one you have in /usr/include, which is the wrong version.

Closing this, as this is not expected to work.  Pybind11 has changed their API significantly between 2.0 and 2.2.  We use the 2.2 API.

**Comment by gijzelaerr** [comment]
ah sorry for missing that. thanks!
